name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  start-rate-limit:
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X GET /rate_limit -q .resources.core.remaining | tee -a $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  parallel:
    needs: [start-rate-limit]
    strategy:
      fail-fast: false
      matrix:
        index: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
    runs-on: ubuntu-latest
    steps:
      - uses: int128/issues-action@v2
        with:
          context: true
          post-comment: Hello ${{ matrix.index }}
      - run: gh api -X GET /rate_limit -q .resources.core.remaining | tee -a $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  final-rate-limit:
    needs: [parallel]
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X GET /rate_limit -q .resources.core.remaining | tee -a $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
